task = input("Enter a task to save: ") 
file = open("tasks.txt", "a") 
file.write(task + "\n") 
file.close() 
print("Task saved!") 
print("") 
print("All saved tasks:") 
file = open("tasks.txt", "r") 
content = file.read() 
file.close() 
print(content)